version: '3'

services:
  api_users:
    image: ofi.userserviceapi:latest
    ports:
      - "8080:80"
    networks:
      - mynetwork

  api_tasks:
    image: ofi.taskserviceapi:latest
    ports:
      - "8081:80"
    networks:
      - mynetwork

  ui_angular:
    image: workofi-ui:latest
    ports:
     - "8082:80"
    networks:
     - mynetwork

  redis_tasks:
    image: redis
    ports:
      - "6379:6379"
    networks:
     - mynetwork
  redis_users:
    image: redis
    ports:
      - "6380:6379"
    networks:
     - mynetwork
  rabbitmq:
   image: "rabbitmq:management"
   ports:
    - "15672:15672"
    - "5672:5672"
   networks:
    - mynetwork
   environment:
     RABBITMQ_DEFAULT_USER: "guest"
     RABBITMQ_DEFAULT_PASS: "guest"

networks:
  mynetwork:
    driver: bridge
