apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: api-tasks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
