apiVersion: v1
kind: Pod
metadata:
  name: ui-pod
  labels:
    app: ui
spec:
  containers:
  - name: ui-container
    image: workofi-ui
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4200
