apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
